name: "Multi event pipeline"

on:
    push: #Event : Whenever a push is made to the repository
        branches:
            - main
            - test
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    on-push: #Job 1 name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: #List of steps
            - name: "Running on master/test push"
              run: echo "Running on master/test push"

    on-pull-request: #Job 2 name
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"
    
    on-workflow-dispatch: #Job 3 name
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatch"
              run: echo "Running on workflow dispatch"