name: "Multi event pipeline"

on:
    push: #Event : Whenever a push is made to the repository
        branches:
            - main


jobs:
    on-push: #Job name
        runs-on: ubuntu-latest
        steps: #List of steps
            - name: "Running on master push"
              run: echo "Running on master push"