name: "Multi event pipeline"

on:
    push: #Event : Whenever a push is made to the repository
        branches:
            - main
            - test
    pull_request:
        branches:
            - main

jobs:
    on-push: #Job name
        runs-on: ubuntu-latest
        steps: #List of steps
            - name: "Running on master/test push"
              run: echo "Running on master/test push"
              
    on-pull-request: #Job name
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"